export const PHOTOGRAPHERS = ['Stephanie', 'Matt', 'Molly', 'Beth', 'Andrew', 'Lauren', 'Emily'];
export const ASSISTANTS = ['Victoria', 'Siena', 'Meg', 'Carmen', 'Margaret', 'Simone', 'Colleen', 'Kristen', 'Jaime', 'Sam', 'Cori', 'Marianna', 'Lauren'];
export const ADMINS = ['Matt', 'Stephanie', 'Carrie'];

export const STATUSES = ['Needs Photographers Scheduled', 'Scheduled', 'Rain Watch', 'Completed'];

export const TYPE_COLORS = {
  'Fall Picture Day': 'bg-[#DDE8D2] text-zinc-800 border-[#AEBB9E]',
  'Spring Picture Day': 'bg-emerald-50 text-emerald-900 border-emerald-200',
  Seniors: 'bg-violet-50 text-violet-900 border-violet-200',
  Sports: 'bg-amber-50 text-amber-900 border-amber-200',
  'Rain Date': 'bg-sky-50 text-sky-900 border-sky-200',
  'Makeup Day': 'bg-rose-50 text-rose-900 border-rose-200',
  'Call or Meeting': 'bg-zinc-100 text-zinc-800 border-zinc-200',
  'Photo Booth': 'bg-pink-50 text-pink-900 border-pink-200',
  Headshots: 'bg-orange-50 text-orange-900 border-orange-200',
  'Family Photos': 'bg-lime-50 text-lime-900 border-lime-200',
  'Special Event': 'bg-indigo-50 text-indigo-900 border-indigo-200',
  'Edit Day': 'bg-teal-50 text-teal-900 border-teal-200'
};

export const SCHOOL_ALIASES = {
  'Nisky - Craig Elem': ['Craig Elementary', 'Nisky Craig', 'Craig Elem'],
  'Shen - Skano': ['Skano', 'Skano Elementary'],
  'The Academies (AA/G)': ['Academy', 'Albany Academy', 'The Academies'],
  'Cairo-Durham MS/HS': ['Cairo Middle School', 'Cairo High School'],
  'Cairo-Durham Elem': ['Cairo Elementary'],
  'Kid\'s Express': ['Kids Express', "Kid's Express"],
  'Nisky - Rosendale Elem': ['Rosendale', 'Rosendale Elementary']
};

export const historicalScheduleEvents = [
  // ------------------------------------------------------------
  // SEPTEMBER 2025
  // ------------------------------------------------------------
  {
    id: "2025-09-01-labor-day",
    date: "2025-09-01",
    sourceTitle: "LABOR DAY",
    canonicalSchoolName: null,
    eventType: "Special Event",
    status: "Completed",
    photographers: [],
    assistants: [],
    features: [],
    notes: "Holiday / no school scheduling.",
  },
  {
    id: "2025-09-02-academy-seniors",
    date: "2025-09-02",
    sourceTitle: "Academy Seniors",
    canonicalSchoolName: "The Academies Seniors",
    eventType: "Seniors",
    status: "Completed",
    photographers: ["Stephanie", "Matt", "Emily"],
    assistants: [],
    features: [],
    notes: "Beth dentist 3-4. Beth edit day / Emily 8 hours edit.",
  },
  {
    id: "2025-09-02-waterford-fall-sports",
    date: "2025-09-02",
    sourceTitle: "Waterford Halfmoon Fall Sports",
    canonicalSchoolName: null,
    eventType: "Sports",
    status: "Completed",
    photographers: ["Andrew", "Molly"],
    assistants: [],
    features: [],
    notes: "Sports account; not linked to school seed by default.",
  },
  {
    id: "2025-09-03-cairo-seniors",
    date: "2025-09-03",
    sourceTitle: "Cairo Seniors",
    canonicalSchoolName: "Cairo-Durham Seniors",
    eventType: "Seniors",
    status: "Completed",
    photographers: ["Molly", "Andrew"],
    assistants: [],
    features: [],
    notes: "Senior portraits.",
  },
  {
    id: "2025-09-03-academy-seniors",
    date: "2025-09-03",
    sourceTitle: "Academy Seniors",
    canonicalSchoolName: "The Academies Seniors",
    eventType: "Seniors",
    status: "Completed",
    photographers: ["Stephanie", "Matt", "Emily"],
    assistants: [],
    features: [],
    notes: "Emily morning. Emily 8 hours.",
  },
  {
    id: "2025-09-03-academy-fall-sports",
    date: "2025-09-03",
    sourceTitle: "Academy Fall Sports AFTERNOON 2-4pm",
    canonicalSchoolName: null,
    eventType: "Sports",
    status: "Completed",
    photographers: ["Lauren"],
    assistants: ["Emily"],
    features: [],
    notes: "Afternoon 2-4pm. Sports account.",
  },
  {
    id: "2025-09-03-latham-christian-first-day",
    date: "2025-09-03",
    sourceTitle: "Latham Christian Academy First Day",
    canonicalSchoolName: "Latham Christian Academy",
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Beth"],
    assistants: [],
    features: [],
    notes: "First day photos.",
  },
  {
    id: "2025-09-03-lcs-makeup-laila",
    date: "2025-09-03",
    sourceTitle: "Laila Fowler LCS Make Up 4:30",
    canonicalSchoolName: "Latham Christian Academy",
    eventType: "Makeup Day",
    status: "Completed",
    photographers: ["Stephanie"],
    assistants: [],
    features: [],
    notes: "Laila Fowler makeup at 4:30. Contact details preserved in source PDF only.",
  },
  {
    id: "2025-09-03-lcs-makeup-miarh",
    date: "2025-09-03",
    sourceTitle: "Miarh LCS Make Up 4:45",
    canonicalSchoolName: "Latham Christian Academy",
    eventType: "Makeup Day",
    status: "Completed",
    photographers: ["Stephanie"],
    assistants: [],
    features: [],
    notes: "Miarh makeup at 4:45. Contact details preserved in source PDF only.",
  },
  {
    id: "2025-09-03-kids-express-first-day",
    date: "2025-09-03",
    sourceTitle: "Kids Express First Day AM",
    canonicalSchoolName: "Kid's Express",
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Matt"],
    assistants: [],
    features: [],
    notes: "First day AM. Liz called Carrie and confirmed correct date of 9/3.",
  },
  {
    id: "2025-09-04-cairo-seniors",
    date: "2025-09-04",
    sourceTitle: "Cairo Seniors",
    canonicalSchoolName: "Cairo-Durham Seniors",
    eventType: "Seniors",
    status: "Completed",
    photographers: ["Molly", "Andrew", "Emily"],
    assistants: [],
    features: [],
    notes: "Emily 8 hour day.",
  },
  {
    id: "2025-09-04-academy-upper-school-pictures",
    date: "2025-09-04",
    sourceTitle: "Academy Upper School Pictures (New/Mentor/Upper School)",
    canonicalSchoolName: "The Academies (AA/G)",
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Stephanie", "Beth"],
    assistants: [],
    features: [],
    notes: "New/Mentor/Upper School pictures.",
  },
  {
    id: "2025-09-04-kids-express-first-day",
    date: "2025-09-04",
    sourceTitle: "Kids Express First Day",
    canonicalSchoolName: "Kid's Express",
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Matt"],
    assistants: [],
    features: [],
    notes: "Source note repeats that Liz called Carrie confirming 9/3 date.",
  },
  {
    id: "2025-09-04-ls-veneer-training",
    date: "2025-09-04",
    sourceTitle: "Important Computer Training for L&S Veneer",
    canonicalSchoolName: null,
    eventType: "Call or Meeting",
    status: "Completed",
    photographers: ["Stephanie"],
    assistants: [],
    features: [],
    notes: "Meeting link in source PDF.",
  },
  {
    id: "2025-09-04-qr-assistant-interview",
    date: "2025-09-04",
    sourceTitle: "Samantha Pugliese Interview QR Assistant 7:00 PM",
    canonicalSchoolName: null,
    eventType: "Call or Meeting",
    status: "Completed",
    photographers: ["Stephanie"],
    assistants: [],
    features: [],
    notes: "QR Assistant interview at 7:00 PM. Source says Steph + ?.",
  },
  {
    id: "2025-09-05-academy-first-day-stock",
    date: "2025-09-05",
    sourceTitle: "Academy First Day Stock Photos",
    canonicalSchoolName: "The Academies (AA/G)",
    eventType: "Special Event",
    status: "Completed",
    photographers: ["Stephanie"],
    assistants: [],
    features: [],
    notes: "First day stock photos.",
  },
  {
    id: "2025-09-05-northville-fall-sports",
    date: "2025-09-05",
    sourceTitle: "Northville Fall Sports",
    canonicalSchoolName: null,
    eventType: "Sports",
    status: "Completed",
    photographers: ["Beth"],
    assistants: ["Emily"],
    features: [],
    notes: "Emily 3 hour shoot / 5 hour edit time.",
  },
  {
    id: "2025-09-05-cairo-seniors",
    date: "2025-09-05",
    sourceTitle: "Cairo Seniors",
    canonicalSchoolName: "Cairo-Durham Seniors",
    eventType: "Seniors",
    status: "Completed",
    photographers: ["Molly", "Andrew"],
    assistants: [],
    features: [],
    notes: "Senior portraits.",
  },
  {
    id: "2025-09-05-siena-photo-booth-dropoff",
    date: "2025-09-05",
    sourceTitle: "DROP OFF: Photo Booth at Siena at NOON",
    canonicalSchoolName: null,
    eventType: "Photo Booth",
    status: "Completed",
    photographers: ["Matt"],
    assistants: [],
    features: ["Photo Booth Add-On"],
    notes: "Drop off at noon.",
  },
  {
    id: "2025-09-06-duanesburg-seniors",
    date: "2025-09-06",
    sourceTitle: "Duanesburg Seniors",
    canonicalSchoolName: "Duanesburg Seniors",
    eventType: "Seniors",
    status: "Completed",
    photographers: ["Stephanie", "Beth"],
    assistants: [],
    features: [],
    notes: "Published note in source PDF.",
  },
  {
    id: "2025-09-07-duanesburg-seniors",
    date: "2025-09-07",
    sourceTitle: "Duanesburg Seniors",
    canonicalSchoolName: "Duanesburg Seniors",
    eventType: "Seniors",
    status: "Completed",
    photographers: ["Stephanie", "Andrew", "Emily"],
    assistants: [],
    features: [],
    notes: "Emily 8 hour shoot.",
  },
  {
    id: "2025-09-08-duanesburg-fall-sports",
    date: "2025-09-08",
    sourceTitle: "Duanesburg Fall Sports 7IRM",
    canonicalSchoolName: null,
    eventType: "Sports",
    status: "Completed",
    photographers: ["Stephanie"],
    assistants: ["Emily"],
    features: [],
    notes: "Beth / Andrew / Molly edit day.",
  },
  {
    id: "2025-09-08-cha-consulting-meeting",
    date: "2025-09-08",
    sourceTitle: "CHA Consulting Marketing director meeting MS Teams",
    canonicalSchoolName: null,
    eventType: "Call or Meeting",
    status: "Completed",
    photographers: ["Stephanie"],
    assistants: [],
    features: [],
    notes: "11:30. Meeting details in source PDF.",
  },
  {
    id: "2025-09-08-school-team-huddle",
    date: "2025-09-08",
    sourceTitle: "School Team Huddle 11am",
    canonicalSchoolName: null,
    eventType: "Call or Meeting",
    status: "Completed",
    photographers: [],
    assistants: [],
    features: [],
    notes: "11am Google Meet in source PDF.",
  },
  {
    id: "2025-09-09-bkw-fall-sports",
    date: "2025-09-09",
    sourceTitle: "BKW Fall Sports 9IRM",
    canonicalSchoolName: null,
    eventType: "Sports",
    status: "Completed",
    photographers: ["Stephanie"],
    assistants: ["Emily"],
    features: [],
    notes: "Beth not available before 9am.",
  },
  {
    id: "2025-09-09-capital-region-boces-schoharie",
    date: "2025-09-09",
    sourceTitle: "Capital Region BOCES Schoharie (1 Team)",
    canonicalSchoolName: null,
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Beth"],
    assistants: [],
    features: [],
    notes: "BOCES account not currently in school seed list.",
  },
  {
    id: "2025-09-09-kindercare-nisky",
    date: "2025-09-09",
    sourceTitle: "Kindercare Nisky (2 Teams) 18IRM",
    canonicalSchoolName: "Kindercare Clifton Park",
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Molly", "Andrew", "Emily"],
    assistants: ["Victoria"],
    features: [],
    notes: "Source says Kindercare Nisky; school seed currently has Kindercare Clifton Park. Needs canonical review.",
  },
  {
    id: "2025-09-09-siena-photo-booth-pickup",
    date: "2025-09-09",
    sourceTitle: "PICK UP: Photo Booth at Siena MORNING",
    canonicalSchoolName: null,
    eventType: "Photo Booth",
    status: "Completed",
    photographers: ["Matt"],
    assistants: [],
    features: ["Photo Booth Add-On"],
    notes: "Picked up Monday per source note.",
  },
  {
    id: "2025-09-10-green-tech",
    date: "2025-09-10",
    sourceTitle: "Green Tech MS/HS (1 Team) 10IRM",
    canonicalSchoolName: "Green Tech MS/HS",
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Beth"],
    assistants: ["Margaret", "Simone"],
    features: [],
    notes: "Added 08/21. Switched to MW on 09/01.",
  },
  {
    id: "2025-09-10-albany-academy-upper",
    date: "2025-09-10",
    sourceTitle: "Albany Academy Upper School 110IRM",
    canonicalSchoolName: "The Academies (AA/G)",
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Stephanie"],
    assistants: [],
    features: [],
    notes: "1 at upper school, 2 at lower school.",
  },
  {
    id: "2025-09-10-albany-academy-lower",
    date: "2025-09-10",
    sourceTitle: "Albany Academy Lower School",
    canonicalSchoolName: "The Academies (AA/G)",
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Andrew", "Molly", "Matt"],
    assistants: ["Emily"],
    features: ["Group Photos"],
    notes: "Class pics. Emily 8 hour.",
  },
  {
    id: "2025-09-10-senior-makeups",
    date: "2025-09-10",
    sourceTitle: "Herba Senior Makeup / Eva Lu / Koral Hernandez Senior Makeup",
    canonicalSchoolName: null,
    eventType: "Seniors",
    status: "Completed",
    photographers: ["Stephanie"],
    assistants: [],
    features: [],
    notes: "Multiple senior makeup appointments; contact details kept in source PDF.",
  },
  {
    id: "2025-09-11-green-tech",
    date: "2025-09-11",
    sourceTitle: "Green Tech MS/HS (1 Team) 10IRM",
    canonicalSchoolName: "Green Tech MS/HS",
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Beth"],
    assistants: ["Simone"],
    features: [],
    notes: "Steph edit day. Assistant preference notes in source.",
  },
  {
    id: "2025-09-11-tsl-guilderland",
    date: "2025-09-11",
    sourceTitle: "TSL Daycare Guilderland (1 Team)",
    canonicalSchoolName: "TSL Guilderland",
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Emily", "Lauren"],
    assistants: ["Victoria"],
    features: [],
    notes: "Shoot 4 hours / edit 4 hours.",
  },
  {
    id: "2025-09-11-cairo-middle",
    date: "2025-09-11",
    sourceTitle: "Cairo Middle School (1 Photog) 37IRM",
    canonicalSchoolName: "Cairo-Durham MS/HS",
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Molly"],
    assistants: [],
    features: [],
    notes: "Middle school portion.",
  },
  {
    id: "2025-09-11-cairo-high",
    date: "2025-09-11",
    sourceTitle: "Cairo High School (1 Photog) 37IRM",
    canonicalSchoolName: "Cairo-Durham MS/HS",
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Andrew"],
    assistants: [],
    features: [],
    notes: "High school portion.",
  },
  {
    id: "2025-09-11-reviews",
    date: "2025-09-11",
    sourceTitle: "REVIEWS",
    canonicalSchoolName: null,
    eventType: "Call or Meeting",
    status: "Completed",
    photographers: ["Andrew", "Molly", "Matt", "Stephanie"],
    assistants: [],
    features: [],
    notes: "Internal reviews.",
  },
  {
    id: "2025-09-12-cairo-middle",
    date: "2025-09-12",
    sourceTitle: "Cairo Middle School (1 Photog) 37IRM",
    canonicalSchoolName: "Cairo-Durham MS/HS",
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Molly"],
    assistants: [],
    features: [],
    notes: "Middle school portion.",
  },
  {
    id: "2025-09-12-cairo-high",
    date: "2025-09-12",
    sourceTitle: "Cairo High School (1 Photog) 37IRM",
    canonicalSchoolName: "Cairo-Durham MS/HS",
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Andrew"],
    assistants: [],
    features: [],
    notes: "High school portion.",
  },
  {
    id: "2025-09-12-cairo-fall-sports",
    date: "2025-09-12",
    sourceTitle: "Cairo Fall Sports 19IRM",
    canonicalSchoolName: null,
    eventType: "Sports",
    status: "Completed",
    photographers: ["Andrew", "Molly"],
    assistants: [],
    features: [],
    notes: "Sports account.",
  },
  {
    id: "2025-09-12-okte",
    date: "2025-09-12",
    sourceTitle: "Okte Elementary (2 Teams) 99IRM",
    canonicalSchoolName: "Shen - Okte",
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Beth", "Stephanie"],
    assistants: ["Emily", "Marianna"],
    features: ["Outdoor"],
    notes: "Emily 6 hour shoot / 2 hours edit.",
  },
  {
    id: "2025-09-13-holden-rivera-senior",
    date: "2025-09-13",
    sourceTitle: "Holden Rivera Senior Portraits",
    canonicalSchoolName: null,
    eventType: "Seniors",
    status: "Completed",
    photographers: ["Stephanie"],
    assistants: [],
    features: [],
    notes: "Senior portrait session.",
  },
  {
    id: "2025-09-15-cairo-elementary-pk2",
    date: "2025-09-15",
    sourceTitle: "Cairo Elementary PK-2 (1 Team) 80IRM",
    canonicalSchoolName: "Cairo-Durham Elem",
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Molly"],
    assistants: ["Margaret"],
    features: [],
    notes: "PK-2 portion. Added 08/21; switched to MW on 09/01.",
  },
  {
    id: "2025-09-15-boces-albany-cte-main",
    date: "2025-09-15",
    sourceTitle: "Capital Region BOCES Albany CTE Main (2 Teams)",
    canonicalSchoolName: null,
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Emily", "Matt"],
    assistants: [],
    features: [],
    notes: "Emily 6 hours shoot / 2 hours edit. BOCES account not in seed list.",
  },
  {
    id: "2025-09-15-boces-albany-extension",
    date: "2025-09-15",
    sourceTitle: "Capital Region BOCES Albany Extension (1 Team)",
    canonicalSchoolName: null,
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Andrew"],
    assistants: [],
    features: [],
    notes: "BOCES account not in seed list.",
  },
  {
    id: "2025-09-15-northville-picture-day",
    date: "2025-09-15",
    sourceTitle: "Northville Picture Day (2 Teams & Class Pics) 84IRM",
    canonicalSchoolName: "Northville",
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Stephanie", "Beth"],
    assistants: ["Lauren"],
    features: ["Group Photos"],
    notes: "Class pics. Assistant VD removed 09/07 per source.",
  },
  {
    id: "2025-09-15-october-scheduling-call",
    date: "2025-09-15",
    sourceTitle: "OCTOBER SCHEDULING CALL 7:30PM",
    canonicalSchoolName: null,
    eventType: "Call or Meeting",
    status: "Completed",
    photographers: [],
    assistants: [],
    features: [],
    notes: "Google Meet link in source PDF.",
  },
  {
    id: "2025-09-15-qr-candidate-interview",
    date: "2025-09-15",
    sourceTitle: "Jaime King QR Candidate interview 7:00 pm",
    canonicalSchoolName: null,
    eventType: "Call or Meeting",
    status: "Completed",
    photographers: ["Stephanie"],
    assistants: [],
    features: [],
    notes: "QR candidate interview.",
  },
  {
    id: "2025-09-16-hoosic-seniors",
    date: "2025-09-16",
    sourceTitle: "Hoosic Valley Seniors Afternoon",
    canonicalSchoolName: "Hoosic Seniors",
    eventType: "Seniors",
    status: "Completed",
    photographers: ["Andrew"],
    assistants: [],
    features: [],
    notes: "Andrew appointment noted.",
  },
  {
    id: "2025-09-16-hoosic-underclass",
    date: "2025-09-16",
    sourceTitle: "Hoosic Valley Underclass (1 Photog) 43IRM",
    canonicalSchoolName: "Hoosic Valley MS/HS",
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Emily", "Matt"],
    assistants: [],
    features: [],
    notes: "No WiFi in Hoosic. Switched to LR then MM per source notes.",
  },
  {
    id: "2025-09-16-cairo-elementary-35",
    date: "2025-09-16",
    sourceTitle: "Cairo Elementary 3-5 (1 Team) 80IRM",
    canonicalSchoolName: "Cairo-Durham Elem",
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Molly"],
    assistants: ["Margaret"],
    features: [],
    notes: "3-5 portion. Added 08/21; switched to MW on 09/01.",
  },
  {
    id: "2025-09-16-okte-rain-date",
    date: "2025-09-16",
    sourceTitle: "Okte Rain Date (2 Teams)",
    canonicalSchoolName: "Shen - Okte",
    eventType: "Rain Date",
    status: "Completed",
    photographers: ["Stephanie", "Beth"],
    assistants: ["Carmen", "Victoria"],
    features: [],
    notes: "Rain date. Beth edit day also noted.",
  },
  {
    id: "2025-09-17-hoosic-seniors",
    date: "2025-09-17",
    sourceTitle: "Hoosic Valley Seniors Afternoon",
    canonicalSchoolName: "Hoosic Seniors",
    eventType: "Seniors",
    status: "Completed",
    photographers: ["Andrew"],
    assistants: [],
    features: [],
    notes: "Senior portraits.",
  },
  {
    id: "2025-09-17-hoosic-underclass",
    date: "2025-09-17",
    sourceTitle: "Hoosic Valley Underclass (1 Photog) 43IRM",
    canonicalSchoolName: "Hoosic Valley MS/HS",
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Emily"],
    assistants: [],
    features: [],
    notes: "Underclass photos.",
  },
  {
    id: "2025-09-17-duanesburg-mshs-day1",
    date: "2025-09-17",
    sourceTitle: "Duanesburg MS/HS Day 1 (1 Photog) 37IRM",
    canonicalSchoolName: "D'burg MS/HS",
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Stephanie"],
    assistants: [],
    features: [],
    notes: "Day 1.",
  },
  {
    id: "2025-09-17-rosendale",
    date: "2025-09-17",
    sourceTitle: "NEW Rosendale Elementary [Nisky] (2 Teams) ~75IRM",
    canonicalSchoolName: "Nisky - Rosendale Elem",
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Molly", "Beth"],
    assistants: ["Margaret", "Victoria", "Lauren"],
    features: ["Group Photos"],
    notes: "School requested group class photos; photographer added for class photos.",
  },
  {
    id: "2025-09-18-hoosic-seniors-day",
    date: "2025-09-18",
    sourceTitle: "Hoosic Valley Seniors Day",
    canonicalSchoolName: "Hoosic Seniors",
    eventType: "Seniors",
    status: "Completed",
    photographers: ["Andrew"],
    assistants: ["Carmen"],
    features: [],
    notes: "Helper needs camera. Added by MT/source notes.",
  },
  {
    id: "2025-09-18-waterford-halfmoon-elementary",
    date: "2025-09-18",
    sourceTitle: "Waterford-Halfmoon Elementary (2 Teams) 40IRM",
    canonicalSchoolName: "Waterford Halfmoon Elem",
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Matt", "Beth"],
    assistants: ["Margaret", "Victoria"],
    features: [],
    notes: "Molly edit day / Emily edit day 8 hours.",
  },
  {
    id: "2025-09-18-siena-photo-booth-dropoff",
    date: "2025-09-18",
    sourceTitle: "Siena Photo Booth Drop Off EVENING",
    canonicalSchoolName: null,
    eventType: "Photo Booth",
    status: "Completed",
    photographers: ["Lauren"],
    assistants: [],
    features: ["Photo Booth Add-On"],
    notes: "Evening drop off.",
  },
  {
    id: "2025-09-18-duanesburg-mshs-day2",
    date: "2025-09-18",
    sourceTitle: "Duanesburg MS/HS Day 2 (1 Photog) 37IRM",
    canonicalSchoolName: "D'burg MS/HS",
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Lauren"],
    assistants: [],
    features: [],
    notes: "Day 2.",
  },
  {
    id: "2025-09-19-duanesburg-elementary",
    date: "2025-09-19",
    sourceTitle: "Duanesburg Elementary (2 Teams) 98IRM",
    canonicalSchoolName: "D'burg Elementary",
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Molly", "Beth"],
    assistants: ["Emily"],
    features: ["Group Photos"],
    notes: "Class pics. Steph Binghamton. Emily 5 hours shoot / 3 hours edit.",
  },
  {
    id: "2025-09-19-siena-career-fair",
    date: "2025-09-19",
    sourceTitle: "Siena Career Fair 12:30-3 (1 Photog)",
    canonicalSchoolName: null,
    eventType: "Special Event",
    status: "Completed",
    photographers: ["Matt"],
    assistants: [],
    features: [],
    notes: "Andrew edit day.",
  },
  {
    id: "2025-09-20-lodge-fest",
    date: "2025-09-20",
    sourceTitle: "Lodge Fest",
    canonicalSchoolName: null,
    eventType: "Special Event",
    status: "Completed",
    photographers: ["Stephanie"],
    assistants: [],
    features: [],
    notes: "Special event.",
  },
  {
    id: "2025-09-20-abby-russo-senior",
    date: "2025-09-20",
    sourceTitle: "Abby Russo Senior Portraits Nisky then Congress Park 8:30",
    canonicalSchoolName: null,
    eventType: "Seniors",
    status: "Completed",
    photographers: ["Stephanie"],
    assistants: [],
    features: [],
    notes: "Senior portraits at Nisky then Congress Park.",
  },
  {
    id: "2025-09-22-waterford-mshs-seniors",
    date: "2025-09-22",
    sourceTitle: "Waterford-Halfmoon MS/HS & Seniors Afterschool (1 Team?) 21IRM",
    canonicalSchoolName: "Waterford MS/HS",
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Molly", "Emily"],
    assistants: [],
    features: [],
    notes: "Afterschool. Beth not available after 3pm.",
  },
  {
    id: "2025-09-22-walter-b-howard",
    date: "2025-09-22",
    sourceTitle: "Walter B. Howard Elementary (1 Team) 47IRM",
    canonicalSchoolName: "Walter B Howard",
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Beth"],
    assistants: ["Meg"],
    features: ["Outdoor"],
    notes: "Andrew edit day / Steph edit day.",
  },
  {
    id: "2025-09-22-sicilia-delorenzo-senior",
    date: "2025-09-22",
    sourceTitle: "Sicilia Delorenzo Senior Photos after school",
    canonicalSchoolName: null,
    eventType: "Seniors",
    status: "Completed",
    photographers: ["Stephanie"],
    assistants: [],
    features: [],
    notes: "Senior photos after school.",
  },
  {
    id: "2025-09-23-waterford-mshs-seniors",
    date: "2025-09-23",
    sourceTitle: "Waterford-Halfmoon MS/HS & Seniors Afterschool (1 Team?) 21IRM",
    canonicalSchoolName: "Waterford MS/HS",
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Molly", "Emily"],
    assistants: [],
    features: [],
    notes: "Afterschool. Hold Kid's Express Day 1 also listed.",
  },
  {
    id: "2025-09-23-kids-express-day1",
    date: "2025-09-23",
    sourceTitle: "HOLD Kid's Express Day 1 38IRM",
    canonicalSchoolName: "Kid's Express",
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Matt"],
    assistants: ["Meg"],
    features: [],
    notes: "Beth edit day. Meg added 09/21.",
  },
  {
    id: "2025-09-23-gardner-dickinson",
    date: "2025-09-23",
    sourceTitle: "Gardner Dickinson Elementary/Middle (2 Photogs + 1 Asst) 57IRM",
    canonicalSchoolName: "Gardner Dickinson",
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Stephanie", "Andrew"],
    assistants: ["Sam"],
    features: [],
    notes: "Source note: We don't need an assistant! SM.",
  },
  {
    id: "2025-09-23-walter-b-howard-rain",
    date: "2025-09-23",
    sourceTitle: "Walter B. Howard Elementary RAIN",
    canonicalSchoolName: "Walter B Howard",
    eventType: "Rain Date",
    status: "Completed",
    photographers: ["Beth"],
    assistants: ["Carmen"],
    features: [],
    notes: "Rain date.",
  },
  {
    id: "2025-09-24-glencliff",
    date: "2025-09-24",
    sourceTitle: "Glencliff Elementary (2 Teams) 76IRM",
    canonicalSchoolName: "Glencliff Elementary",
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Stephanie", "Beth"],
    assistants: [],
    features: [],
    notes: "Two-team day.",
  },
  {
    id: "2025-09-24-kids-express-day2",
    date: "2025-09-24",
    sourceTitle: "HOLD Kid's Express Day 2 38IRM",
    canonicalSchoolName: "Kid's Express",
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Matt"],
    assistants: ["Meg", "Sam"],
    features: [],
    notes: "Molly edit day. Sam added 09/09, Meg added 09/21.",
  },
  {
    id: "2025-09-24-loudonville-christian",
    date: "2025-09-24",
    sourceTitle: "Loudonville Christian School (1 Team) 30IRM",
    canonicalSchoolName: "Loudonville Christian",
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Andrew"],
    assistants: ["Lauren"],
    features: ["Group Photos"],
    notes: "Emily edit day. Lauren send edits to Matt.",
  },
  {
    id: "2025-09-24-cha-headshot",
    date: "2025-09-24",
    sourceTitle: "CHA Headshot Sahin Studio 3:30",
    canonicalSchoolName: null,
    eventType: "Headshots",
    status: "Completed",
    photographers: ["Stephanie"],
    assistants: [],
    features: [],
    notes: "Studio headshot at 3:30.",
  },
  {
    id: "2025-09-25-karigon",
    date: "2025-09-25",
    sourceTitle: "Karigon Elementary (2 Teams) 88IRM",
    canonicalSchoolName: "Shen - Karigon",
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Molly", "Andrew"],
    assistants: ["Meg", "Colleen"],
    features: [],
    notes: "Switched SS with CH on 09/11.",
  },
  {
    id: "2025-09-25-skano",
    date: "2025-09-25",
    sourceTitle: "Skano Elementary (3! Teams) 94IRM",
    canonicalSchoolName: "Shen - Skano",
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Beth", "Stephanie", "Emily"],
    assistants: ["Lauren", "Victoria", "Cori"],
    features: ["Outdoor"],
    notes: "Changed to indoor on 9/23; Matt texted photographers. Might have Cori be assistant.",
  },
  {
    id: "2025-09-26-bkw-secondary",
    date: "2025-09-26",
    sourceTitle: "BKW Secondary (1 Team) 33IRM",
    canonicalSchoolName: "BKW Secondary",
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Lauren"],
    assistants: ["Matt"],
    features: [],
    notes: "Matt 2nd shooter if needed.",
  },
  {
    id: "2025-09-26-craig",
    date: "2025-09-26",
    sourceTitle: "NEW Craig Elementary School [Nisky] (2 Teams) ~75IRM",
    canonicalSchoolName: "Nisky - Craig Elem",
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Molly", "Stephanie"],
    assistants: ["Carmen", "Victoria"],
    features: [],
    notes: "Emily edit day. Expect Craig to end at 1PM latest per Google Calendar.",
  },
  {
    id: "2025-09-26-orenda",
    date: "2025-09-26",
    sourceTitle: "Orenda Elementary (2 Teams) 85IRM",
    canonicalSchoolName: "Shen - Orenda",
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Beth", "Andrew"],
    assistants: ["Margaret", "Simone"],
    features: ["Outdoor"],
    notes: "Simone assisting.",
  },
  {
    id: "2025-09-27-schalmont-soccer",
    date: "2025-09-27",
    sourceTitle: "Schalmont Soccer - 30 teams - new league",
    canonicalSchoolName: null,
    eventType: "Sports",
    status: "Completed",
    photographers: ["Stephanie", "Molly", "Andrew"],
    assistants: [],
    features: [],
    notes: "No Lauren on location.",
  },
  {
    id: "2025-09-28-ohanlon-family",
    date: "2025-09-28",
    sourceTitle: "O'Hanlon Family Portraits 3:00 Schoharie",
    canonicalSchoolName: null,
    eventType: "Family Photos",
    status: "Completed",
    photographers: ["Stephanie"],
    assistants: [],
    features: [],
    notes: "No Lauren on location.",
  },
  {
    id: "2025-09-28-nys-shrm",
    date: "2025-09-28",
    sourceTitle: "NYS SHRM Conference 7:00-1:00",
    canonicalSchoolName: null,
    eventType: "Special Event",
    status: "Completed",
    photographers: ["Lauren"],
    assistants: [],
    features: [],
    notes: "Scheduled by Studio.",
  },
  {
    id: "2025-09-29-shen-united-methodist-day1",
    date: "2025-09-29",
    sourceTitle: "NEW Shen United Methodist Preschool Day 1 (1 Team)",
    canonicalSchoolName: "Shen United Methodist PK",
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Molly"],
    assistants: ["Colleen"],
    features: [],
    notes: "Colleen added per Homebase.",
  },
  {
    id: "2025-09-29-chango",
    date: "2025-09-29",
    sourceTitle: "NEW Chango Elementary [Shen] (2 Teams) ~80IRM",
    canonicalSchoolName: "Shen - Chango (NEW)",
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Beth", "Stephanie"],
    assistants: ["Kristen", "Jaime"],
    features: ["Composite"],
    notes: "Collages at Chango, NOT group class pictures.",
  },
  {
    id: "2025-09-29-tesago",
    date: "2025-09-29",
    sourceTitle: "Tesago Elementary (2 Teams) 67IRM",
    canonicalSchoolName: "Shen - Tesago",
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Andrew", "Emily"],
    assistants: ["Simone", "Meg"],
    features: [],
    notes: "Two-team day.",
  },
  {
    id: "2025-09-29-nys-shrm",
    date: "2025-09-29",
    sourceTitle: "NYS SHRM Conference 7:00-5:00",
    canonicalSchoolName: null,
    eventType: "Special Event",
    status: "Completed",
    photographers: ["Lauren"],
    assistants: [],
    features: [],
    notes: "Scheduled by Studio.",
  },
  {
    id: "2025-09-29-school-team-huddle",
    date: "2025-09-29",
    sourceTitle: "SCHOOL TEAM HUDDLE CALL 8PM",
    canonicalSchoolName: null,
    eventType: "Call or Meeting",
    status: "Completed",
    photographers: [],
    assistants: [],
    features: [],
    notes: "Google Meet link in source PDF.",
  },
  {
    id: "2025-09-30-shen-united-methodist-day2",
    date: "2025-09-30",
    sourceTitle: "NEW Shen United Methodist Preschool Day 2 (1 Team)",
    canonicalSchoolName: "Shen United Methodist PK",
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Molly"],
    assistants: [],
    features: [],
    notes: "Jaime cut 9/29. Source assistant N/A.",
  },
  {
    id: "2025-09-30-hudson-valley-consortium-day1",
    date: "2025-09-30",
    sourceTitle: "Hudson Valley Consortium Day 1 (1 Team) 21IRM",
    canonicalSchoolName: "Hudson Valley Consortium",
    eventType: "Fall Picture Day",
    status: "Completed",
    photographers: ["Emily"],
    assistants: [],
    features: [],
    notes: "Emily shoot 4 hours / edit 4 hours.",
  },
  {
    id: "2025-09-30-skano-rain-date",
    date: "2025-09-30",
    sourceTitle: "Skano Rain Date",
    canonicalSchoolName: "Shen - Skano",
    eventType: "Rain Date",
    status: "Completed",
    photographers: ["Beth", "Stephanie"],
    assistants: [],
    features: [],
    notes: "Beth edit day / Steph edit day also noted.",
  },
  {
    id: "2025-09-30-union-career-fair",
    date: "2025-09-30",
    sourceTitle: "Union College Career Fair EVENING",
    canonicalSchoolName: null,
    eventType: "Special Event",
    status: "Completed",
    photographers: ["Andrew"],
    assistants: [],
    features: [],
    notes: "Evening event.",
  },
];

function extractIrm(title) {
  const match = String(title || '').match(/~?(\d+)\s*IRM/i);
  return match ? Number(match[1]) : null;
}

function extractTime(title) {
  const text = String(title || '');
  const timeMatch = text.match(/\b(\d{1,2})(?::(\d{2}))?\s*(AM|PM|am|pm)\b/);
  if (timeMatch) {
    const minutes = timeMatch[2] ? `:${timeMatch[2]}` : ':00';
    return `${timeMatch[1]}${minutes} ${timeMatch[3].toUpperCase()}`;
  }
  if (/\bMORNING\b/i.test(text)) return 'Morning';
  if (/\bAFTERNOON\b/i.test(text)) return 'Afternoon';
  if (/\bEVENING\b/i.test(text)) return 'Evening';
  if (/\bNOON\b/i.test(text)) return 'Noon';
  if (/\bAll Day\b/i.test(text) || /LABOR DAY/i.test(text)) return 'All Day';
  return 'TBD';
}

function buildHistory(event) {
  const pieces = [];
  if (event.canonicalSchoolName) pieces.push(`Canonical school: ${event.canonicalSchoolName}`);
  if (event.sourceTitle && event.sourceTitle !== event.canonicalSchoolName) pieces.push(`Source title: ${event.sourceTitle}`);
  if (event.features?.length) pieces.push(`Features: ${event.features.join(', ')}`);
  return pieces.join(' · ');
}

export const EVENTS = historicalScheduleEvents.map((event) => ({
  id: event.id,
  date: event.date,
  title: event.sourceTitle,
  canonicalSchool: event.canonicalSchoolName || '',
  type: event.eventType,
  status: event.status || 'Scheduled',
  time: extractTime(event.sourceTitle),
  irm: extractIrm(event.sourceTitle),
  photographers: event.photographers || [],
  assistants: event.assistants || [],
  features: event.features || [],
  notes: event.notes || '',
  rainInfo: event.eventType === 'Rain Date' ? event.notes || 'Rain date.' : '',
  history: buildHistory(event)
}));
